style:
    script:
        - cp /keys/.pypirc ~/.pypirc
        - virtualenv ../env
        - source ../env/bin/activate
        - XDG_CACHE_HOME=/cache pip3 install -U pip wheel setuptools isort docformatter black flake8 check-manifest
        - XDG_CACHE_HOME=/cache pip3 install -U "git+https://github.com/pretix/pretix.git@master#egg=pretix"
        - python setup.py develop
        - black --check .
        - isort -c .
        - flake8 .
        - check-manifest .
    tags:
        - python3
pypi:
    script:
        - cp /keys/.pypirc ~/.pypirc
        - virtualenv /tmp/env
        - source /tmp/env/bin/activate
        - XDG_CACHE_HOME=/cache pip3 install -U pip wheel setuptools twine build pretix-plugin-build
        - python -m build
        - check-manifest .twine check dist/*
        - twine upload dist/*
    tags:
        - python3
    only:
        - pypi
    artifacts:
        paths:
            - dist/
